---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: argocd-notifications-cm
spec:
  secretStoreRef:
    name: platform
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
  data:
    - secretKey: gitlab
      remoteRef:
        key: /ep/argocd/gitlab
        conversionStrategy: Default
    - secretKey: slack-token
      remoteRef:
        key: /ep/argocd/slack
        conversionStrategy: Default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  subscriptions: |
    - recipients:
      - slack:int-mn-aws-ops
      triggers:
      - on-health-degraded
      - on-sync-failed
      - on-deployed
    - recipients:
      - gitlab:""
      triggers:
      - on-sync-failed
      - on-deployed
  # https://docs.gitlab.com/ee/ci/jobs/#the-order-of-jobs-in-a-pipeline
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      oncePer: app.status.sync.revision
      send:
      - app-sync-status
      - gitlab-deployment-status
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
  trigger.on-sync-failed	: |
    - description: Application is sync failed. Triggered once per commit.
      oncePer: app.status.sync.revision
      send:
      - app-sync-status
      - gitlab-deployment-status
      when: app.status.operationState.phase in ['Failed'] and app.status.health.status == 'Degraded'
  trigger.on-health-degraded: |
    - description: Application is synced and healthy. Triggered once per commit.
      oncePer: app.status.sync.revision
      send:
      - app-sync-status
      when: app.status.health.status == 'Degraded'

  template.gitlab-deployment-status: |
    webhook:
      gitlab:
        method: POST
        path: /projects/48/deployments
        body: |
          {
            {{if eq .app.status.operationState.phase "Running"}} "status": "running"{{end}}
            {{if eq .app.status.operationState.phase "Succeeded"}} "status": "success"{{end}}
            {{if eq .app.status.operationState.phase "Error"}} "status": "failed"{{end}}
            {{if eq .app.status.operationState.phase "Failed"}} "status": "failed"{{end}},
            "environment": "development",
            "sha": "{{.app.status.operationState.operation.sync.revision}}",
            "ref": "notifications_setup",
            "tag": "false"
          }

  template.app-sync-status: |
    message: |
      Application {{.app.metadata.name}} sync is {{.app.status.sync.status}}.
      Application details: {{.app.spec.source.repoURL}}/applications/{{.app.metadata.name}}.
    slack:
      attachments: |
        [{
          "title": "{{.app.metadata.name}}",
          "title_link": "/applications/{{.app.metadata.name}}",
          {{if eq .app.status.health.status "Healthy"}}"color": "#18be52"{{end}}
          {{if eq .app.status.health.status "Degraded"}}"color": "#ff0047"{{end}},
          "fields": [{
            "title": "Sync Status",
            "value": "{{.app.status.sync.status}}",
            "short": true
          }, {
            "title": "App Health",
            "value": "{{.app.status.health.status}}""
            "short": true
          }, {
            "title": "Repository",
            "value": "{{.app.spec.source.repoURL}}",
            "short": true
          }]
        }]

  service.webhook.gitlab: |
    url: https://mns.gitlab.schubergphilis.com/api/v4
    headers:
    - name: PRIVATE-TOKEN
      value: $gitlab
    - name: Content-type
      value: application/json

  service.slack: |
    token: $slack-token
    username: argocd
