replicaCount: 1

domainName: ""
environment: ""
provider: ""
roleArn: ""
serviceAccount: ""

image:
  repository: mbezemer/techmarket-k8s-node-app
  tag: 0.0.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - example.localdev.me
  tls: []

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
