promtail:
  config:
    clients:
      - url: http://loki-gateway/loki/api/v1/push
        tenant_id: admins
      - url: http://loki-gateway/loki/api/v1/push
        tenant_id: fih
    snippets:
      pipeline_stages:
        - cri: {}
        - match:
            selector: '{team=fih"}'
            stages:
              - tenant:
                  label: "team"
        - match:
            selector: '{team=admins"}'
            stages:
              - tenant:
                  label: "team"
        - output:
            source: message

loki:
  gateway:
    autoscaling:
      enabled: true
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: internal
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
        service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
        service.beta.kubernetes.io/aws-load-balancer-attributes: deletion_protection.enabled=true,load_balancing.cross_zone.enabled=true
  loki:
    auth_enabled: true
