apiVersion: v1
kind: Service
metadata:
  name: {{ template "node-app.fullname" . }}
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ template "node-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ template "node-app.chart" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ template "node-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
